NAME: davit_v1
NUM_CLASSES: 0
#IMAGE_SIZE: [384, 384]
IMAGE_SIZE: [480, 480]
LOAD_PRETRAINED: true
PRETRAINED: ''
PRETRAINED_LAYERS: '*'
IMAGE_MEAN: [0.485, 0.456, 0.406]
IMAGE_STD: [0.229, 0.224, 0.225]
SPEC:
  DROP_RATE: 0.1
  DROP_PATH_RATE: 0.2
  PATCH_SIZE: [7, 3, 3, 3]
  PATCH_STRIDE: [4, 2, 2, 2]
  PATCH_PADDING: [3, 1, 1, 1]
  PATCH_PRENORM: [false, true, true, true]
  DIM_EMBED: [256, 512, 1024, 2048]
  NUM_HEADS: [8, 16, 32, 64]
  NUM_GROUPS: [8, 16, 32, 64]
  DEPTHS: [1, 1, 9, 1]
  WINDOW_SIZE: 12
  ENABLE_CHECKPOINT: true